name: brm_shell_checker
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check size script
        id: size_checker
        run: |
          modules_ok=0
          modules=($(find . -type f -name '*.sh' -exec echo '{}' \;))
          for mod in "${modules[@]}"; do line_numbers=$(wc -l < "${mod}"); [[ $line_numbers -gt 300 ]]  && modules_ok=1; done
          [[ $modules_ok -eq 0 ]] && echo ok || exit 1